tag_names = [
  "Technology", "Programming", "Ruby on Rails", "Web Development", "Design", "Art", "Photography",
  "Mobile Development", "iOS", "Android", "UI/UX", "Frontend Development", "Backend Development",
  "Machine Learning", "Data Science", "Artificial Intelligence", "Blockchain", "Cybersecurity",
  "Cloud Computing", "DevOps", "Internet of Things", "Virtual Reality", "Augmented Reality",
  "Game Development", "Software Engineering", "Product Management", "Startup", "Entrepreneurship",
  "Digital Marketing", "Content Marketing", "Social Media", "SEO", "E-commerce", "Graphic Design",
  "Illustration", "Animation", "Film", "Music", "Literature", "Poetry", "Philosophy", "History",
  "Science", "Space Exploration", "Environment", "Health", "Fitness", "Cooking", "Travel", "Fashion",
  "Python", "JavaScript", "Java", "C++", "C#", "PHP", "Swift", "Kotlin", "TypeScript", "Ruby",
  "Go", "R", "Objective-C", "Scala", "Perl", "Rust", "Haskell", "Lua", "SQL", "HTML", "CSS",
  "Assembly", "Shell", "Dart", "MATLAB", "VB.NET", "Groovy", "Clojure", "Elixir", "F#", "Julia",
  "Ada", "Fortran", "COBOL", "Lisp", "Scheme", "Prolog", "Smalltalk", "Erlang", "PL/SQL", "Tcl",
  "Bash", "ActionScript", "CoffeeScript", "D", "Dylan", "Forth", "LabVIEW", "Objective-J",
  "Pascal", "PowerShell", "PureScript", "Racket", "Rebol", "Scratch", "Verilog", "VHDL", "Zig",
  "Django", "Flask", "Express.js", "React", "Angular", "Vue.js", "Spring", "Laravel", "Symfony",
  "CodeIgniter", "Zend Framework", "ASP.NET Core", "ASP.NET MVC", "Node.js", "Meteor", "Ember.js",
  "Flutter", "Xamarin", "RubyMotion", "Cocoa Touch", "Qt", "Electron", "TensorFlow", "PyTorch",
  "Keras", "Scikit-learn", "ASP.NET Web Forms", "Struts", "Hibernate", "Play Framework", "Grails",
  "CakePHP", "Slim", "NestJS", "FastAPI", "Next.js", "Nuxt.js", "Sails.js", "LoopBack", "Feathers",
  "AdonisJS", "Phoenix", "Sinatra", "Padrino", "Ramaze", "Merb", "Grape", "Volt", "Camping",
  "Quantum Computing", "Edge Computing", "5G", "Biotechnology", "Renewable Energy", "Smart Cities",
  "Autonomous Vehicles", "Robotics", "Natural Language Processing", "Computer Vision", "Biometrics",
  "Cryptocurrency", "Digital Privacy", "Fintech", "Healthtech", "Edtech", "Agritech", "Gaming",
  "Mobile Apps", "Hardware", "Networking", "Artificial General Intelligence", "Smart Home",
  "Wearable Technology", "Space Exploration", "Satellite Technology", "3D Printing", "Quantified Self",
  "Biohacking", "Smart Agriculture", "Smart Manufacturing", "Clean Technology", "ARKit", "Core ML", "Metal", "SpriteKit", "SceneKit", "MapKit", "HealthKit", "WatchKit", "CarPlay", "HomeKit",
  "SwiftUI", "Combine", "TensorFlow.js", "D3.js", "React Native", "Vue Native", "Ionic", "Apache Cordova", "PhoneGap",
  "Xamarin.Forms", "Unity", "Unreal Engine", "Godot Engine", "OpenCV", "OpenGL", "DirectX", "Vulkan", "SDL", "SFML",
  "Blender", "Maya", "3ds Max", "Unity3D", "GIMP", "Inkscape", "Adobe Illustrator", "Adobe Photoshop", "Adobe Premiere",
  "Final Cut Pro", "Avid Media Composer", "Logic Pro", "Ableton Live", "FL Studio", "Cinema 4D", "ZBrush", "Autodesk SketchBook",
  "Substance Painter", "Procreate", "Rhino", "Grasshopper", "Autodesk Revit", "AutoCAD", "SketchUp", "Fusion 360",
  "SolidWorks", "CATIA", "ANSYS", "Matplotlib", "Seaborn", "Bokeh", "Plotly", "ggplot2", "Plotly", "Highcharts",
  "Tableau", "Microsoft Power BI", "QlikView", "Looker", "Dataiku", "RapidMiner", "Alteryx", "Knime", "SAP Analytics Cloud",
  "IBM Cognos Analytics", "ThoughtSpot", "Databricks", "Snowflake", "Redshift", "BigQuery", "Teradata", "Vertica",
  "Cassandra", "HBase", "MongoDB", "Firebase", "Elasticsearch", "Redis", "Couchbase", "Neo4j", "ArangoDB", "DynamoDB",
  "PostgreSQL", "MariaDB", "SQLite", "CrateDB", "TimescaleDB", "CockroachDB", "Cosmos DB", "Google Cloud Spanner",
  "Amazon RDS", "Azure SQL Database", "IBM Db2", "Oracle Database", "MySQL", "SQL Server", "Sybase", "Informix",
  "NoSQL", "NewSQL", "Relational Database Management System", "Document Store", "Key-Value Store", "Column Store",
  "Graph Database", "Time Series Database", "Wide-Column Store", "Blob Store", "Search Engine", "Database Management System", "GraphQL", "RESTful API", "SOAP", "Microservices", "Serverless", "Containerization", "Docker", "Kubernetes",
  "Ansible", "Chef", "Puppet", "Terraform", "Jenkins", "CircleCI", "Travis CI", "GitLab CI/CD", "GitHub Actions",
  "Continuous Integration", "Continuous Deployment", "Version Control", "Git", "Mercurial", "Subversion",
  "Code Review", "Static Code Analysis", "Linting", "Unit Testing", "Integration Testing", "End-to-End Testing",
  "Test Automation", "Performance Testing", "Security Testing", "Accessibility Testing", "A/B Testing", "Usability Testing",
  "Code Quality", "Code Coverage", "Code Documentation", "Technical Debt", "Refactoring", "Design Patterns", "SOLID Principles",
  "Clean Code", "Domain-Driven Design", "Test-Driven Development", "Behavior-Driven Development", "Agile Methodology",
  "Scrum", "Kanban", "Lean Software Development", "Extreme Programming", "Pair Programming", "Mob Programming",
  "Agile Coaching", "Product Owner", "Scrum Master", "Agile Team", "Agile Transformation", "Digital Transformation",
  "Lean Startup", "Minimum Viable Product (MVP)", "Product-Market Fit", "Lean Canvas", "Business Model Canvas",
  "Customer Development", "User Research", "User Experience Research", "Design Thinking", "Human-Centered Design",
  "User-Centered Design", "Service Design", "Design Sprint", "Innovation", "Creativity", "Problem Solving",
  "Critical Thinking", "Decision Making", "Project Management", "Time Management", "Resource Management",
  "Risk Management", "Stakeholder Management", "Communication Skills", "Leadership Skills", "Teamwork",
  "Conflict Resolution", "Emotional Intelligence", "Remote Work", "Freelancing", "Gig Economy", "Digital Nomadism",
  "Work-Life Balance", "Self-Development", "Personal Growth", "Mindfulness", "Wellness", "Healthy Lifestyle",
  "Mental Health", "Stress Management", "Self-Care", "Productivity", "Goal Setting", "Habit Formation",
  "Learning Strategies", "Skill Acquisition", "Education", "Online Learning", "Self-Paced Learning", "MOOCs",
  "Certifications", "Professional Development", "Career Advancement", "Job Search", "Interview Preparation",
  "Resume Writing", "Networking", "Personal Branding", "Public Speaking", "Writing Skills", "Content Creation",
  "Copywriting", "Blogging", "Podcasting", "Vlogging", "Social Media Marketing", "Influencer Marketing",
  "Email Marketing", "Search Engine Marketing", "Affiliate Marketing", "Video Marketing", "Web Analytics",
  "Conversion Rate Optimization", "Lead Generation", "Customer Relationship Management (CRM)", "Sales Funnel",
  "Customer Journey", "Customer Segmentation", "Marketing Automation", "Customer Support", "Customer Success",
  "Feedback Management", "Community Building", "Brand Management", "Brand Identity", "Brand Strategy",
  "Brand Awareness", "Brand Loyalty", "Brand Advocacy", "Competitor Analysis", "Market Research",
  "SWOT Analysis", "Business Strategy", "Business Planning", "Business Development", "Sales Strategy",
  "Customer Acquisition", "Customer Retention", "Revenue Generation", "Profitability", "Financial Management",
  "Budgeting", "Cost Control", "Financial Forecasting", "Investment Management", "Asset Management",
  "Risk Analysis", "Financial Reporting", "Financial Modeling", "Accounting", "Bookkeeping", "Taxation",
  "Auditing", "Compliance", "Regulatory Affairs", "Legal Compliance", "Data Privacy", "GDPR Compliance",
  "HIPAA Compliance", "PCI DSS Compliance", "ISO Compliance", "Accessibility Compliance", "Standards Compliance",
  "Environmental Compliance", "Occupational Health and Safety (OHS) Compliance", "Quality Management",
  "ISO 9001", "Six Sigma", "Total Quality Management (TQM)", "Customer Satisfaction", "Supplier Management",
  "Supply Chain Management", "Logistics", "Inventory Management", "Warehouse Management", "Procurement",
  "Sourcing", "Supplier Relationship Management (SRM)", "Demand Forecasting", "Production Planning",
  "Just-in-Time (JIT)", "Lean Manufacturing", "Kaizen", "5S Methodology", "Root Cause Analysis",
  "Corrective Action", "Preventive Action", "Safety Management", "Emergency Preparedness", "Crisis Management",
  "Incident Management", "Business Continuity Planning", "Disaster Recovery", "Risk Assessment",
  "Risk Mitigation", "Asset Protection", "Facility Management", "Building Maintenance", "Space Planning",
  "Energy Management", "Sustainability", "Environmental Management", "Waste Management", "Carbon Footprint Reduction",
  "Renewable Energy Integration", "Energy Efficiency", "Green Building", "LEED Certification", "Biodiversity Conservation",
  "Ecotourism", "Conservation Agriculture", "Sustainable Forestry", "Water Resource Management", "Clean Water Access",
  "Sanitation", "Hygiene Promotion", "Wastewater Treatment", "Air Pollution Control", "Climate Change Mitigation",
  "Adaptation Strategies", "Resilience Building", "Carbon Markets", "Carbon Offsetting", "Climate Finance",
  "Climate Risk Management", "Ecosystem Restoration", "Nature-Based Solutions", "Sustainable Development Goals (SDGs)",
  "Circular Economy", "Zero Waste", "Corporate Social Responsibility (CSR)", "Social Impact", "Community Development",
  "Social Equity", "Inclusive Growth", "Fair Trade", "Ethical Sourcing", "Labor Rights", "Human Rights",
  "Diversity and Inclusion", "Gender Equality", "Accessibility", "Equal Opportunity", "Social Justice",
  "Youth Empowerment", "Education Equality", "Global Citizenship", "Peacebuilding", "Conflict Resolution",
  "Nonviolent Communication", "Interfaith Dialogue", "Intercultural Understanding", "Ethical Leadership",
  "Integrity", "Transparency", "Accountability", "Good Governance", "Rule of Law", "Freedom of Speech",
  "Freedom of Press", "Freedom of Assembly", "Civil Liberties", "Democracy", "Electoral Reform", "Political Participation",
  "Civic Engagement", "Citizenship Education", "Volunteerism", "Community Service", "Humanitarian Aid",
  "Emergency Relief", "Disaster Response", "Refugee Assistance", "Humanitarian Advocacy", "Peacekeeping",
  "Conflict Transformation", "Mediation", "Arbitration", "International Law", "Human Rights Law",
  "Humanitarian Law", "Environmental Law", "Trade Law", "Intellectual Property Law", "Contract Law",
  "Criminal Law", "Family Law", "Labor Law", "Corporate Law", "Tax Law", "Banking Law", "Insurance Law",
  "Privacy Law", "Data Protection Law", "Cyber Law", "Health Law", "Public Health Policy", "Healthcare Management",
  "Healthcare Financing", "Health Information Systems", "Electronic Health Records (EHR)", "Telemedicine",
  "E-Health", "Mental Health Services", "Primary Healthcare", "Preventive Healthcare", "Health Promotion",
  "Health Education", "Nutrition", "Physical Activity", "Disease Prevention", "Maternal and Child Health",
  "Reproductive Health", "Family Planning", "HIV/AIDS Prevention", "Sexual and Reproductive Health and Rights (SRHR)",
  "Global Health Governance", "Universal Health Coverage", "Health Equity", "Social Determinants of Health",
  "One Health", "Public Health Emergency Preparedness", "Epidemiology", "Surveillance", "Outbreak Investigation",
  "Health Risk Assessment", "Health Communication", "Health Advocacy", "Health Diplomacy", "Health Systems Strengthening",
  "Healthcare Quality Improvement", "Patient Safety", "Clinical Governance", "Evidence-Based Practice",
  "Healthcare Innovation", "Health Technology Assessment", "Health Economics", "Health Financing", "Health Insurance",
  "Healthcare Regulation", "Healthcare Ethics", "Medical Law", "Health Human Resources", "Health Workforce Development",
  "Health Professional Education", "Medical Schools", "Nursing Schools", "Pharmacy Schools", "Public Health Schools",
  "Health Research", "Biomedical Research", "Clinical Research", "Translational Research", "Health Data Science",
  "Health Informatics", "Health Analytics", "Precision Medicine", "Personalized Medicine", "Genomics", "Pharmacogenomics",
  "Medical Imaging", "Medical Devices", "Health Biotechnology", "Regenerative Medicine", "Stem Cell Therapy",
  "Gene Therapy", "Immunotherapy", "Vaccines", "Antibiotics", "Antiviral Drugs", "Antimalarial Drugs",
  "Antiretroviral Drugs", "Cancer Therapeutics", "Cardiovascular Therapeutics", "Respiratory Therapeutics",
  "Neurological Therapeutics", "Psychiatric Therapeutics", "Pain Management", "Dermatological Therapeutics",
  "Gastrointestinal Therapeutics", "Endocrine Therapeutics", "Rheumatological Therapeutics", "Ophthalmological Therapeutics",
  "Otolaryngological Therapeutics", "Orthopedic Therapeutics", "Urological Therapeutics", "Obstetrical Therapeutics",
  "Gynecological Therapeutics", "Pediatric Therapeutics", "Geriatric Therapeutics", "Rehabilitation Therapeutics",
  "Sports Medicine", "Emergency Medicine", "Intensive Care Medicine", "Anesthesiology", "Surgery",
  "Cardiothoracic Surgery", "Neurosurgery", "Orthopedic Surgery", "Plastic Surgery", "General Surgery",
  "Gynecological Surgery", "Urological Surgery", "Ophthalmological Surgery", "Otolaryngological Surgery",
  "Dental Surgery", "Maxillofacial Surgery", "Pediatric Surgery", "Trauma Surgery", "Transplant Surgery",
  "Vascular Surgery", "Colon and Rectal Surgery", "Gastrointestinal Surgery", "Endocrine Surgery",
  "Breast Surgery", "Surgical Oncology", "Surgical Pathology", "Surgical Anatomy", "Surgical Physiology",
  "Surgical Pharmacology", "Surgical Microbiology", "Surgical Immunology", "Surgical Genetics", "Surgical Biomaterials",
  "Surgical Instruments", "Surgical Techniques", "Surgical Training", "Surgical Education", "Surgical Research",
  "Surgical Ethics", "Surgical History", "Orthodontics", "Endodontics", "Periodontics", "Prosthodontics",
  "Pediatric Dentistry", "Oral and Maxillofacial Radiology", "Oral and Maxillofacial Pathology", "Oral and Maxillofacial Surgery",
  "Dental Public Health", "Dental Hygiene", "Dental Assisting", "Dental Laboratory Technology", "Oral Health Education",
  "Oral Health Promotion", "Oral Health Policy", "Oral Health Advocacy", "Oral Health Research", "Oral Health Informatics",
  "Oral Health Economics", "Oral Health Financing", "Oral Health Systems Strengthening", "Oral Health Human Resources",
  "Oral Health Workforce Development", "Oral Health Professional Education", "Dental Schools", "Oral Health Research Institutes",
  "Public Dental Health", "Private Dental Practice", "Community Dental Practice", "Dental Hospitals", "Specialty Dental Clinics",
  "Mobile Dental Units", "Tele-Dentistry", "Digital Dentistry", "CAD/CAM Dentistry", "Laser Dentistry", "Implant Dentistry",
  "Cosmetic Dentistry", "Restorative Dentistry", "Preventive Dentistry", "Pediatric Dentistry", "Orthodontic Dentistry",
  "Periodontal Dentistry", "Endodontic Dentistry", "Prosthodontic Dentistry", "Oral Surgery", "Oral Pathology",
  "Oral Medicine", "Geriatric Dentistry", "Orofacial Pain Management", "Dental Radiology", "Forensic Dentistry",
  "Dental Anatomy", "Dental Histology", "Dental Embryology", "Dental Physiology", "Dental Microbiology", "Dental Pharmacology",
  "Dental Genetics", "Dental Biomaterials", "Dental Instruments", "Dental Techniques", "Dental Training", "Dental Education",
  "Dental Research", "Dental Ethics", "Dental History"
]

tag_names.each do |name|
  Tag.create(name: name)
end

puts "==================== Tags seeded successfully! ==========================="