
category_names = [
  "Technology", "Programming", "Web Development", "Design", "Art", "Photography",
  "Mobile Development", "Machine Learning", "Data Science", "Blockchain", "Cybersecurity",
  "Cloud Computing", "Internet of Things", "Game Development", "Startup", "Digital Marketing",
  "Content Marketing", "Social Media", "SEO", "E-commerce", "Graphic Design",
  "Illustration", "Animation", "Film", "Music", "Literature", "Poetry", "Philosophy", "History",
  "Science", "Space Exploration", "Environment", "Health", "Fitness", "Cooking", "Travel", "Fashion",
  "Big Data", "Data Engineering", "Data Warehousing", "Data Lakes", "Data Integration",
  "Data Governance", "Data Quality", "Data Analytics", "Data Visualization",
  "Data Mining", "Predictive Analytics", "Prescriptive Analytics",
  "Real-time Analytics", "Stream Processing", "Batch Processing",
  "ETL (Extract, Transform, Load)", "ELT (Extract, Load, Transform)",
  "Data Pipelines", "Data Modeling", "Data Architecture",
  "Data Storage", "NoSQL Databases", "SQL Databases",
  "NewSQL Databases", "Columnar Databases", "Document Databases",
  "Graph Databases", "Time Series Databases", "Key-Value Stores",
  "In-memory Databases", "Distributed Databases", "Data Security",
  "Data Privacy", "Data Ethics", "Data Compliance",
  "Data Protection", "Data Masking", "Data Encryption",
  "Data Anonymization", "Data Access Control", "Data Sovereignty",
  "Data Residency", "Data Lifecycle Management", "Data Catalogs",
  "Data Lineage", "Data Profiling", "Data Cleansing",
  "Data Enrichment", "Data Imputation", "Data Wrangling",
  "Data Normalization", "Data Aggregation", "Data Transformation",
  "Data Deduplication", "Data Compression", "Data Indexing",
  "Data Partitioning", "Data Sharding", "Data Replication",
  "Data Backup", "Data Recovery", "Data Migration",
  "Data Archiving", "Data Exploration", "Data Discovery",
  "Data Storytelling", "Data Journalism", "Data Literacy",
  "Data Science", "Data Scientists", "Data Analysts",
  "Data Engineers", "Data Architects", "Business Intelligence",
  "Data-driven Decision Making", "Data-driven Innovation",
  "Data-driven Marketing", "Data-driven Operations",
  "Data-driven Product Development", "Data-driven Strategy",
  "Data Monetization", "Data as a Service (DaaS)",
  "Data Governance Frameworks", "Data Governance Policies",
  "Data Governance Processes", "Data Governance Tools",
  "Data Governance Best Practices", "Data Governance Compliance",
  "Data Governance Risks", "Data Governance Benefits",
  "Data Governance Challenges", "Data Governance Trends","Data Science", "Data Analysis", "Data Engineering", "Data Mining", "Data Warehousing",
  "Data Visualization", "Machine Learning", "Deep Learning", "Natural Language Processing",
  "Computer Vision", "Predictive Analytics", "Prescriptive Analytics", "Big Data Analytics",
  "Time Series Analysis", "Exploratory Data Analysis (EDA)", "Statistical Modeling", "Regression Analysis",
  "Classification", "Clustering", "Anomaly Detection", "Association Rule Learning", "Recommender Systems",
  "Dimensionality Reduction", "Feature Engineering", "Feature Selection", "Model Evaluation", "Model Deployment",
  "Model Monitoring", "Model Interpretability", "Model Explainability", "A/B Testing", "Experiment Design",
  "Hypothesis Testing", "Survival Analysis", "Monte Carlo Simulation", "Simulation Modeling", "Optimization",
  "Genetic Algorithms", "Neural Networks", "Convolutional Neural Networks (CNNs)", "Recurrent Neural Networks (RNNs)",
  "Generative Adversarial Networks (GANs)", "Autoencoders", "Transformer Models", "BERT", "GPT", "Quantum Computing", "Edge Computing", "FPGA Development", "Compiler Design", "Emulator Development",
  "Operating Systems", "Kernel Development", "Device Drivers", "File Systems", "Memory Management",
  "Networking Protocols", "Network Security", "Wireless Communication", "Bluetooth Development", "RFID Technology",
  "NFC Technology", "Satellite Communication", "Fiber Optic Technology", "5G Technology", "Telecommunications",
  "Network Function Virtualization (NFV)", "Software-Defined Networking (SDN)", "Internet Protocols", "IPv6",
  "Network Management", "Network Monitoring", "Packet Analysis", "Digital Signal Processing (DSP)", "Audio Processing",
  "Speech Recognition", "Voice Biometrics", "Image Processing", "Video Processing", "Computer Graphics",
  "Rendering Techniques", "Ray Tracing", "Game Engine Development", "Virtual Reality (VR) Development",
  "Augmented Reality (AR) Development", "Immersive Technologies", "Simulations", "Physics Engines",
  "Math Libraries", "3D Printing Technology", "CAD Software Development", "CAM Software Development",
  "CAE Software Development", "Computer Vision in Manufacturing", "Industrial Automation", "Robotics",
  "Autonomous Systems", "Drone Technology", "Self-Driving Cars", "Intelligent Transportation Systems",
  "Smart Grids", "Renewable Energy Technology", "Solar Energy", "Wind Energy", "Hydropower Technology",
  "Geothermal Energy", "Bioenergy", "Energy Storage Solutions", "Battery Technology", "Fuel Cell Technology",
  "Hydrogen Energy", "Carbon Capture and Storage", "Climate Modeling", "Environmental Monitoring",
  "Pollution Control", "Waste Management", "Circular Economy Solutions", "Sustainable Development",
  "Green Building Technology", "Smart Cities", "Urban Planning", "Transportation Infrastructure",
  "Public Health Informatics", "Epidemiological Modeling", "Healthcare Analytics", "Medical Imaging Analysis",
  "Genomics Research", "Proteomics Research", "Bioinformatics", "Biomechanics", "Biomedical Engineering",
  "Telemedicine Platforms", "Healthcare IoT Solutions", "Electronic Health Records (EHR)", "Medical Devices",
  "Wearable Health Technology", "Telehealth Services", "Digital Therapeutics", "Healthcare Data Privacy",
  "Regulatory Compliance in Healthcare", "Medical Ethics", "Bioethics", "Pharmaceutical Technology",
  "Drug Discovery", "Precision Medicine", "Clinical Trials", "Healthcare Supply Chain Management",
  "Hospital Information Systems (HIS)", "Electronic Medical Records (EMR)", "Healthcare Interoperability",
  "Patient Engagement Solutions", "Personalized Health Management", "Healthcare Blockchain Solutions",
  "Healthcare AI Applications", "Remote Patient Monitoring", "Digital Health Startups", "Telehealth Startups",
  "Healthtech Accelerators", "Healthcare Venture Capital", "Medical Tourism", "Global Health Initiatives",
  "Public Health Campaigns", "Health Education Programs", "Health Equity Solutions", "Social Determinants of Health",
  "Disease Surveillance Systems", "Emergency Preparedness", "Disaster Response Technology", "Humanitarian Technology",
  "Nonprofit Technology", "Community Development Platforms", "Civic Tech Initiatives", "Open Source Projects",
  "Ethical Hacking", "Cyber Threat Intelligence", "Digital Forensics", "Incident Response", "Security Auditing",
  "Security Compliance Frameworks", "Blockchain Security", "IoT Security", "Cloud Security", "Endpoint Security",
  "Identity and Access Management (IAM)", "Security Operations Centers (SOC)", "Security Information and Event Management (SIEM)",
  "Vulnerability Management", "Penetration Testing", "Red Team Operations", "Blue Team Operations", "Purple Team Operations",
  "Threat Hunting", "Cybersecurity Training", "Cybersecurity Certifications", "Privacy-Preserving Technologies",
  "Data Anonymization Techniques", "Privacy-Preserving Machine Learning", "Privacy-Enhancing Technologies (PETs)",
  "Privacy by Design", "Data Ownership Models", "Data Sovereignty Laws", "Data Privacy Regulations", "GDPR Compliance Solutions",
  "HIPAA Compliance Solutions", "CCPA Compliance Solutions", "Data Protection Strategies", "Encryption Algorithms",
  "Cryptographic Protocols", "Secure Multiparty Computation (MPC)", "Homomorphic Encryption", "Zero-Knowledge Proofs (ZKPs)",
  "Differential Privacy", "Federated Learning", "Privacy-Preserving AI Models", "Privacy-Preserving Analytics",
  "Privacy-Preserving Cloud Computing", "Privacy-Preserving Communication Protocols", "Decentralized Identity (DID)",
  "Self-Sovereign Identity (SSI)", "Identity Management Systems", "Digital ID Solutions", "Biometric Authentication",
  "Passwordless Authentication", "Multifactor Authentication (MFA)", "Single Sign-On (SSO)", "OAuth",
  "OpenID Connect", "SAML", "Blockchain-Based Identity Solutions", "Digital Twins", "Smart Sensors",
]

# Create categories
category_names.each do |name|
  Category.create(name: name)
end

puts "================== Categories seeded successfully! =================="
